// Generated by cbindgen — do not edit manually.
// Regenerate with: cd rust && cbindgen --config cbindgen.toml --crate stallari-yrs --output ../Sources/CStallariYRS/include/yrs_ffi.h

#ifndef YRS_FFI_H
#define YRS_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ---------------------------------------------------------------------------
// Opaque types
// ---------------------------------------------------------------------------

typedef struct YrsDoc YrsDoc;
typedef struct YrsTextRef YrsTextRef;
typedef struct YrsAwareness YrsAwareness;

// ---------------------------------------------------------------------------
// Document lifecycle
// ---------------------------------------------------------------------------

/// Create a new Yrs document with a random client ID.
YrsDoc *yrs_doc_new(void);

/// Create a new Yrs document with a specific client ID.
YrsDoc *yrs_doc_new_with_client_id(uint64_t client_id);

/// Free a Yrs document.
void yrs_doc_free(YrsDoc *doc);

/// Get the client ID of a document.
uint64_t yrs_doc_client_id(const YrsDoc *doc);

// ---------------------------------------------------------------------------
// Document state encoding
// ---------------------------------------------------------------------------

/// Encode the full document state as a binary update (V2 encoding).
/// Caller must free the returned buffer with yrs_buf_free.
uint8_t *yrs_doc_encode_state_as_update_v2(const YrsDoc *doc, size_t *out_len);

/// Apply a binary update (V2 encoding) to the document.
/// Returns 0 on success, -1 on failure.
int32_t yrs_doc_apply_update_v2(YrsDoc *doc, const uint8_t *data, size_t len);

/// Encode the document's state vector (for sync negotiation).
/// Caller must free the returned buffer with yrs_buf_free.
uint8_t *yrs_doc_encode_state_vector(const YrsDoc *doc, size_t *out_len);

/// Compute the diff needed to bring a peer from sv_data to current state (V2 encoding).
/// Caller must free the returned buffer with yrs_buf_free.
uint8_t *yrs_doc_encode_diff_v2(const YrsDoc *doc,
                                 const uint8_t *sv_data,
                                 size_t sv_len,
                                 size_t *out_len);

// ---------------------------------------------------------------------------
// Text operations
// ---------------------------------------------------------------------------

/// Get or create a named text type from the document.
/// Do NOT free with yrs_text_free until you are done with it.
YrsTextRef *yrs_doc_get_text(const YrsDoc *doc, const char *name);

/// Free a text reference handle.
void yrs_text_free(YrsTextRef *text);

/// Insert a string at the given index. Returns 0 on success, -1 on failure.
int32_t yrs_text_insert(YrsDoc *doc, const YrsTextRef *text, uint32_t index, const char *value);

/// Delete length characters starting at index. Returns 0 on success, -1 on failure.
int32_t yrs_text_delete(YrsDoc *doc, const YrsTextRef *text, uint32_t index, uint32_t length);

/// Get the full text content as a C string.
/// Caller must free the returned string with yrs_string_free.
char *yrs_text_to_string(const YrsDoc *doc, const YrsTextRef *text);

/// Get the length of the text.
uint32_t yrs_text_len(const YrsDoc *doc, const YrsTextRef *text);

// ---------------------------------------------------------------------------
// Awareness
// ---------------------------------------------------------------------------

/// Create a new awareness instance for the given client ID.
YrsAwareness *yrs_awareness_new(uint64_t client_id);

/// Free an awareness instance.
void yrs_awareness_free(YrsAwareness *awareness);

/// Set the local awareness state (JSON bytes).
void yrs_awareness_set_local_state(YrsAwareness *awareness, const uint8_t *data, size_t len);

/// Apply a remote awareness update.
/// Format: 8 bytes client_id (BE) + 4 bytes state_len (BE) + state bytes.
/// Returns 0 on success, -1 on failure.
int32_t yrs_awareness_apply_update(YrsAwareness *awareness, const uint8_t *data, size_t len);

/// Encode the local awareness state for transmission.
/// Caller must free with yrs_buf_free.
uint8_t *yrs_awareness_encode_update(const YrsAwareness *awareness, size_t *out_len);

/// Get the number of known clients in awareness state.
uint32_t yrs_awareness_client_count(const YrsAwareness *awareness);

/// Get the state for a specific client ID.
/// Returns null if unknown. Caller must free with yrs_buf_free.
uint8_t *yrs_awareness_get_client_state(const YrsAwareness *awareness,
                                         uint64_t client_id,
                                         size_t *out_len);

// ---------------------------------------------------------------------------
// Memory management
// ---------------------------------------------------------------------------

/// Free a buffer returned by any yrs_* function.
void yrs_buf_free(uint8_t *buf);

/// Free a C string returned by yrs_text_to_string.
void yrs_string_free(char *s);

#endif // YRS_FFI_H
